# Generated by Django 5.1.4 on 2024-12-19 14:45

import django.db.models.deletion
import djrazorpay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', djrazorpay.models.RazorpayEntityIdField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=16)),
                ('gstin', models.CharField(max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', djrazorpay.models.RazorpayEntityIdField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=16)),
                ('unit', models.CharField(max_length=16, null=True)),
                ('tax_inclusive', models.BooleanField()),
                ('hsn_code', models.CharField(max_length=16, null=True)),
                ('sac_code', models.CharField(max_length=16, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tax_id', models.CharField(max_length=32, null=True)),
                ('tax_group_id', models.CharField(max_length=32, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', djrazorpay.models.RazorpayEntityIdField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('interval', models.IntegerField()),
                ('period', models.CharField(max_length=16)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djrazorpay.planitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', djrazorpay.models.RazorpayEntityIdField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=16)),
                ('current_start', models.DateTimeField(null=True)),
                ('current_end', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('quantity', models.IntegerField()),
                ('charge_at', models.DateTimeField(null=True)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('auth_attempts', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('paid_count', models.IntegerField()),
                ('customer_notify', models.BooleanField()),
                ('expire_by', models.DateTimeField(null=True)),
                ('short_url', models.URLField()),
                ('has_scheduled_changes', models.BooleanField()),
                ('change_scheduled_at', models.DateTimeField(null=True)),
                ('source', models.CharField(max_length=16)),
                ('offer_id', models.CharField(max_length=32, null=True)),
                ('remaining_count', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djrazorpay.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djrazorpay.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
