# Generated by Django 5.1.4 on 2024-12-24 14:38

import djrazorpay.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrazorpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=djrazorpay.fields.RazorpayDateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=djrazorpay.fields.RazorpayDateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('quarterly', 'QUARTERLY'), ('yearly', 'YEARLY')], help_text='Defines the frequency of the plan.', max_length=16),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='created_at',
            field=djrazorpay.fields.RazorpayDateTimeField(),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='updated_at',
            field=djrazorpay.fields.RazorpayDateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='change_scheduled_at',
            field=djrazorpay.fields.RazorpayDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='charge_at',
            field=djrazorpay.fields.RazorpayDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=djrazorpay.fields.RazorpayDateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_end',
            field=djrazorpay.fields.RazorpayDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_start',
            field=djrazorpay.fields.RazorpayDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_at',
            field=djrazorpay.fields.RazorpayDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ended_at',
            field=djrazorpay.fields.RazorpayDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expire_by',
            field=djrazorpay.fields.RazorpayDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_at',
            field=djrazorpay.fields.RazorpayDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('authenticated', 'AUTHENTICATED'), ('active', 'ACTIVE'), ('pending', 'PENDING'), ('halted', 'HALTED'), ('cancelled', 'CANCELLED'), ('completed', 'COMPLETED'), ('expired', 'EXPIRED')], max_length=16),
        ),
    ]
